name: build kernel library
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup spack
        uses: spack/setup-spack@v2
        with:
          ref: develop
          buildcache: true
          color: true
          path: spack

      - name: install deps w/ spack
        shell: spack-bash {0}
        run: |
          cd tvb_kernels
          spack -e . concretize
          spack -e . install
          spack env activate .
          spack env status
          
      - name: build nanobound library
        shell: spack-bash {0}
        run: |
          cd tvb_kernels
          spack env activate .
          cmake -S . -B build
          pushd build
          make -j2
          popd

      - name: run tests
        shell: spack-bash {0}
        run: |
          cd tvb_kernels
          spack env activate .
          PYTHONPATH=build pytest

      # https://github.com/spack/setup-spack?tab=readme-ov-file#example-caching-your-own-binaries-for-public-repositories
      - name: Push packages and update index
        run: |
          cd tvb_kernels
          spack -e . mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache
          spack -e . buildcache push --base-image ubuntu:22.04 --update-index local-buildcache
        if: ${{ !cancelled() }}
